# NovelNote configuration.
#
# Use with `novelnote --config-file <path>`.
#
# See `novelnote --help` for default config file locations and `novelnote serve --help` for
# additional explanations of enumerated options.

# Timezone to use when writing timestamps.
#
# Used by the `stdout` and `file` log output modes and database backup filenames.
#
# By default, the system timezone is used if it can be determined.
#
# Does not affect how timestamps are stored in the database (always in UTC) or how they are
# displayed to the user (local timezone).
#
# Can also be specified via environment variable `TZ`.
#timezone =

# Admin socket configuration.
#
# By default, `novelnote serve` will, in addition to the HTTP server, start an admin server.
# It binds to a Unix domain socket (Linux and macOS) or named pipe (Windows) that other
# commands, e.g. `novelnote backup`, use to communicate with the main process.
[admin]
# Control whether the admin socket is enabled (default).
#
# Disabling the admin socket is not recommended as it is required for some commands, e.g.
# `novelnote backup`, to function.
#
# Can also be specified via environment variable `ADMIN_SOCKET_ENABLED`.
#
# Default value: true
#enabled = true

# Admin socket path.
#
# On Linux and macOS, this is the path of the Unix domain socket. If the directory for the
# socket does not exist, it is created. For Linux, the default is
# `${XDG_RUNTIME_DIR}/novelnote/novelnote_admin.sock`. For macOS the default is
# `$HOME/Library/Application Support/NovelNote/novelnote_admin.sock`.
#
# On Windows, this is the named pipe namespace. It must start with `\\.\pipe\` and the default
# is `\\.\pipe\NovelNote_Admin`.
#
# Can also be specified via environment variable `ADMIN_SOCKET_PATH`.
#socket_path =

# How long each connection will attempt to read or write before timing out.
#
# See the [`jiff` "friendly" format] for examples of how this may be specified.
#
# The default is 5 seconds. It must be less than 1 minute.
#
# [`jiff` "friendly" format]: https://docs.rs/jiff/latest/jiff/fmt/friendly/index.html
#
# Can also be specified via environment variable `ADMIN_SOCKET_TIMEOUT`.
#
# Default value: "5 seconds"
#timeout = "5 seconds"

# Logging configuration.
[log]
# Where logs should be written to.
#
# Can be one of `stdout` (default), `stdout-no-timestamp`, `journald`, `file`, or `none`.
#
# Can also be specified via environment variable `LOG_OUTPUT`.
#
# Default value: "stdout"
#output = "stdout"

# Filter what is logged.
#
# Each directive can optionally contain a target, span, field(s) (with or without a value),
# and/or level formatted like so: `target[span{field=value}]=level`. For example, `debug` will
# enable all spans and events at the `debug` level or above. Adding a target,
# `novelnote=debug`, limits the spans and events to those created by NovelNote directly.
#
# See the [`tracing_subscriber::EnvFilter`] documentation for a full description of the
# syntax.
#
# [`tracing_subscriber::EnvFilter`]: https://docs.rs/tracing-subscriber/latest/tracing_subscriber/filter/struct.EnvFilter.html#directives
#
# Can also be specified via environment variable `LOG_DIRECTIVES`.
#
# Default value: ["info"]
#directives = ["info"]

# Path to the directory to store the rolling log files in for the `file` log output mode.
#
# If not set, the following directories are used on each platform:
#
# - `${XDG_STATE_HOME:$HOME/.local/state}/novelnote` (Linux)
# - `$HOME/Library/Application Support/NovelNote` (macOS)
# - `%RoamingAppData%/NovelNote/data` (Windows)
#
# If the directory does not exist, it is created.
#
# Can also be specified via environment variable `LOG_FILE_DIRECTORY`.
#file_directory =

# Number of log files to keep.
#
# The `file` log output mode rotates which file it writes to daily. This option determines how
# many log files exist in the log file directory at any given time.
#
# Can also be specified via environment variable `MAX_LOG_FILES`.
#
# Default value: 3
#max_log_files = 3

# SQLite database configuration.
[database]
# Path to the directory where the SQLite database file is placed.
#
# If not set, the following directories are used on each platform:
#
# - `${XDG_DATA_HOME:$HOME/.local/share}/novelnote` (Linux)
# - `$HOME/Library/Application Support/NovelNote` (macOS)
# - `%RoamingAppData%/NovelNote/data` (Windows)
#
# If the directory does not exist, it is created.
#
# The database file itself is named `novelnote.sqlite3`.
#
# Can also be specified via environment variable `DATABASE_DIRECTORY`.
#directory =

# Database backup configuration.
[database.backup]
# Path to the directory where the database backups are placed.
#
# The default is a `backup` directory in the database directory.
#
# If the directory does not exist, it is created.
#
# The path must be valid UTF-8 because it is passed to the admin socket.
#
# Backups are named `novelnote_backup_<ISO-8601 date time>.sqlite3`, with the current date and
# time based on the `timezone` set. For example, a backup on January 2nd, 2026 at 3:45pm would
# have the filename `novelnote_backup_2026-01-02T154500.sqlite3`.
#
# Can also be specified via environment variable `DATABASE_BACKUP_DIRECTORY`.
#directory =

# How many database backups to keep.
#
# Must be at least 1.
#
# Backups are only considered for deletion if the filename matches the format described above.
#
# Can also be specified via environment variable `DATABASE_BACKUP_KEEP_LAST`.
#
# Default value: 5
#keep_last = 5

# HTTP server configuration.
[http]
# IP address the HTTP server should bind to.
#
# Defaults to binding to all interfaces.
#
# Can also be specified via environment variable `HTTP_ADDRESS`.
#
# Default value: "0.0.0.0"
#bind_address = "0.0.0.0"

# TCP port the HTTP server should bind to.
#
# Can also be specified via environment variable `HTTP_PORT`.
#
# Default value: 8080
#port = 8080
