# Containerfile for building the NovelNote container.
#
# Build with Buildah, Podman, or Docker from repository root:
# `buildah build --file deployment/Containerfile --tag novelnote .`

FROM --platform=$BUILDPLATFORM docker.io/library/rust:1 AS chef
WORKDIR /app
ENV CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER=aarch64-linux-gnu-gcc
RUN ["/bin/bash", "-o", "pipefail", "-c", "curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash"]
RUN cargo binstall -y cargo-chef trunk
RUN rustup target add wasm32-unknown-unknown
ARG TARGETPLATFORM
RUN case "$TARGETPLATFORM" in \
    "linux/amd64") echo x86_64-unknown-linux-gnu > /rust_target.txt ;; \
    "linux/arm64/v8") echo aarch64-unknown-linux-gnu > /rust_target.txt && \
       apt-get update && apt-get install -y gcc-aarch64-linux-gnu ;; \
    *) echo "unknown target platform" && exit 1 ;; \
  esac
RUN rustup target add "$(cat /rust_target.txt)"

FROM chef AS planner
COPY Cargo.toml Cargo.lock ./
COPY admin/Cargo.toml ./admin/
COPY database/Cargo.toml ./database/
COPY server/Cargo.toml ./server/
COPY web/Cargo.toml ./web/
COPY src ./src
COPY admin/src ./admin/src
COPY database/src ./database/src
COPY server/src ./server/src
COPY web/src ./web/src
RUN cargo chef prepare --recipe-path recipe.json

FROM chef AS builder
COPY --from=planner /app/recipe.json recipe.json
RUN cargo chef cook \
  --release \
  --target "$(cat /rust_target.txt)" \
  --recipe-path recipe.json
COPY Cargo.toml Cargo.lock ./
COPY admin/Cargo.toml ./admin/
COPY database/Cargo.toml ./database/
COPY server/Cargo.toml ./server/
COPY web/Cargo.toml ./web/
COPY src ./src
COPY admin/src ./admin/src
COPY database/src ./database/src
COPY server/src ./server/src
COPY web/src ./web/src
RUN cargo build \
  --release \
  --target "$(cat /rust_target.txt)"
RUN cp "target/$(cat /rust_target.txt)/release/novelnote" .

FROM chef as builder-frontend
COPY --from=planner /app/recipe.json recipe.json
RUN cargo chef cook \
  --release \
  --package novelnote_web \
  --target wasm32-unknown-unknown \
  --recipe-path recipe.json
COPY Cargo.toml Cargo.lock ./
COPY admin/Cargo.toml ./admin/
COPY database/Cargo.toml ./database/
COPY server/Cargo.toml ./server/
COPY web/Cargo.toml web/index.html ./web/
COPY src ./src
COPY admin/src ./admin/src
COPY database/src ./database/src
COPY server/src ./server/src
COPY web/src ./web/src
RUN trunk build \
  --release \
  --config web/

# Using distroless image for time zone database and CA certificates.
FROM gcr.io/distroless/cc-debian13:latest
COPY --from=builder /app/novelnote /usr/local/bin/
COPY --from=builder-frontend /app/target/dist /usr/local/share/novelnote/dist
ENTRYPOINT [ "/usr/local/bin/novelnote" ]
CMD [ "serve" ]
